version: 0.2

phases:
  build:
    commands:
      - echo "Starting yarn build"
      - yarn
      - yarn build
      - echo "Finished build"
      - ls -la dist/
      - echo "Completed yarn build successfully!"

artifacts:
  files:
    - '**/*'
  base-directory: dist